# yaml-language-server: $schema=test_config.json

uboot_test1:
  fpga:
    power_1_8V: "On"
    power_3_3V: "On"
    power_5_0V: "On"
    S2CCLK_1: 24
    S2CCLK_2: 50
    S2CCLK_3: 16
    S2CCLK_4: 12.288
    S2CCLK_5: 200
    S2CCLK_6: 48
    S2CCLK_7: 100
    S2CCLK_8: 48
    bitfile_fpga1: "null"
    bitfile_fpga2: "C:/Users/MDC_FPGA_3/OneDrive - StarFive Technology International/General/Images/JH8100/0063 JH8100_V0_8_3_CFG1_7_OCT21_EMMC/bit/JH8100_V0_8_3_CFG1_7_OCT21_EMMC_rtlcedd25e_fpgaa7e456d_P1_UV19P_2210221432.bit"